### ISSUE TITLE
请教下大神，多线程调用nanolog打印不是严格时间排序的问题？

### ISSUE THREAD

**Issue by yangqun** [MengRao/NanoLogLite#1]
我在不同的线程那里调用了log打印消息，然后三秒调用一下Nanolog::poll() 输出到硬盘，但是发现不是时间严格排序,
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5195784/156798093-56de8cce-1134-4104-bd17-9be0629e8ad1.png">
请问这个问题有解吗

**Comment by MengRao** [comment]
NanoLogLite这个项目我已经不维护了，建议看看我的另一个项目fmtlog，它不会有这个问题，而且更好用。
