### ISSUE TITLE
打出来的log发现不是严格时序排序有解吗？

### ISSUE THREAD

**Issue by yangqun** [MengRao/NanoLogLite#2]
rt，每隔三秒poll一下，但是发现如果log比较频繁的话，出来的log不是严格时序排序

**Comment by MengRao** [comment]
我在你之前的issue里已经回复了，NanoLogLite这个项目我已经不维护了，建议使用我的另一个项目fmtlog。

**Comment by yangqun** [comment]
> 我在你之前的issue里已经回复了，NanoLogLite这个项目我已经不维护了，建议使用我的另一个项目fmtlog。

难怪我没看到那个issue，我以为是我没发出去，sorry！
